import type { AustralianBank } from "@/lib/types/bank-processing"

export const AUSTRALIAN_BANKS: AustralianBank[] = [
  {
    id: "bankwest",
    name: "Bankwest",
    code: "BWA",
    logo: "/bank-logos/bankwest.png",
    supportedFormats: ["pdf", "csv", "ofx"],
    defaultMappings: [
      {
        id: "bankwest-csv",
        bankId: "bankwest",
        bankName: "Bankwest",
        fileType: "csv",
        mappingRules: {
          dateField: "Date",
          descriptionField: "Description",
          amountField: "Amount",
          balanceField: "Balance",
          referenceField: "Reference",
          dateFormat: "DD/MM/YYYY",
          amountFormat: "positive_negative",
          csvDelimiter: ",",
          skipRows: 0,
          headerRow: 1,
        },
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "westpac",
    name: "Westpac",
    code: "WBC",
    logo: "/bank-logos/westpac.png",
    supportedFormats: ["pdf", "csv", "ofx", "qif"],
    defaultMappings: [
      {
        id: "westpac-csv",
        bankId: "westpac",
        bankName: "Westpac",
        fileType: "csv",
        mappingRules: {
          dateField: "Date",
          descriptionField: "Narrative",
          amountField: "Debit Amount",
          balanceField: "Balance",
          dateFormat: "DD MMM YYYY",
          amountFormat: "debit_credit",
          csvDelimiter: ",",
          skipRows: 1,
          headerRow: 2,
        },
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "defence-bank",
    name: "Defence Bank",
    code: "DBA",
    logo: "/bank-logos/defence-bank.png",
    supportedFormats: ["pdf", "csv"],
    defaultMappings: [
      {
        id: "defence-bank-csv",
        bankId: "defence-bank",
        bankName: "Defence Bank",
        fileType: "csv",
        mappingRules: {
          dateField: "Transaction Date",
          descriptionField: "Description",
          amountField: "Amount",
          balanceField: "Running Balance",
          dateFormat: "YYYY-MM-DD",
          amountFormat: "positive_negative",
          csvDelimiter: ",",
          skipRows: 0,
          headerRow: 1,
        },
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: "up-bank",
    name: "Up Bank",
    code: "UPB",
    logo: "/bank-logos/up-bank.png",
    supportedFormats: ["csv"],
    defaultMappings: [
      {
        id: "up-bank-csv",
        bankId: "up-bank",
        bankName: "Up Bank",
        fileType: "csv",
        mappingRules: {
          dateField: "Date",
          descriptionField: "Description",
          amountField: "Amount (AUD)",
          referenceField: "Tags",
          dateFormat: "YYYY-MM-DD",
          amountFormat: "positive_negative",
          csvDelimiter: ",",
          skipRows: 0,
          headerRow: 1,
        },
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
]
