import type { TransactionCategory } from "@/lib/types/transactions"

export const DEFAULT_CATEGORIES: Omit<TransactionCategory, "id" | "createdAt" | "updatedAt">[] = [
  // Income Categories
  {
    name: "Salary & Wages",
    color: "#10B981",
    icon: "💰",
    type: "income",
    keywords: ["salary", "wage", "payroll", "income", "pay"],
    rules: [
      {
        id: "salary-1",
        field: "description",
        operator: "contains",
        value: "salary",
        weight: 0.9,
        isActive: true,
      },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Investment Income",
    color: "#059669",
    icon: "📈",
    type: "income",
    keywords: ["dividend", "interest", "investment", "capital gain", "stock"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Government Benefits",
    color: "#0D9488",
    icon: "🏛️",
    type: "income",
    keywords: ["centrelink", "pension", "benefit", "allowance", "subsidy"],
    rules: [],
    isSystem: true,
    isActive: true,
  },

  // Housing Categories
  {
    name: "Housing",
    color: "#3B82F6",
    icon: "🏠",
    type: "expense",
    keywords: [],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Rent/Mortgage",
    parentId: "housing",
    color: "#2563EB",
    icon: "🏠",
    type: "expense",
    keywords: ["rent", "mortgage", "housing", "property"],
    rules: [
      {
        id: "rent-1",
        field: "description",
        operator: "contains",
        value: "rent",
        weight: 0.95,
        isActive: true,
      },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Utilities",
    parentId: "housing",
    color: "#1D4ED8",
    icon: "⚡",
    type: "expense",
    keywords: ["electricity", "gas", "water", "internet", "phone", "utility"],
    rules: [
      {
        id: "utilities-1",
        field: "merchant",
        operator: "contains",
        value: "energy",
        weight: 0.8,
        isActive: true,
      },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Home Insurance",
    parentId: "housing",
    color: "#1E40AF",
    icon: "🛡️",
    type: "expense",
    keywords: ["insurance", "home insurance", "property insurance"],
    rules: [],
    isSystem: true,
    isActive: true,
  },

  // Transportation Categories
  {
    name: "Transportation",
    color: "#F59E0B",
    icon: "🚗",
    type: "expense",
    keywords: [],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Fuel",
    parentId: "transportation",
    color: "#D97706",
    icon: "⛽",
    type: "expense",
    keywords: ["fuel", "petrol", "gas", "bp", "shell", "caltex", "mobil"],
    rules: [
      {
        id: "fuel-1",
        field: "merchant",
        operator: "contains",
        value: "bp",
        weight: 0.9,
        isActive: true,
      },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Public Transport",
    parentId: "transportation",
    color: "#B45309",
    icon: "🚌",
    type: "expense",
    keywords: ["opal", "myki", "go card", "transport", "bus", "train", "metro"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Car Payments",
    parentId: "transportation",
    color: "#92400E",
    icon: "🚙",
    type: "expense",
    keywords: ["car loan", "vehicle", "auto loan", "car payment"],
    rules: [],
    isSystem: true,
    isActive: true,
  },

  // Food Categories
  {
    name: "Food & Dining",
    color: "#EF4444",
    icon: "🍽️",
    type: "expense",
    keywords: [],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Groceries",
    parentId: "food",
    color: "#DC2626",
    icon: "🛒",
    type: "expense",
    keywords: ["woolworths", "coles", "aldi", "iga", "grocery", "supermarket"],
    rules: [
      {
        id: "groceries-1",
        field: "merchant",
        operator: "contains",
        value: "woolworths",
        weight: 0.95,
        isActive: true,
      },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Dining Out",
    parentId: "food",
    color: "#B91C1C",
    icon: "🍴",
    type: "expense",
    keywords: ["restaurant", "cafe", "dining", "food", "meal"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Takeaway",
    parentId: "food",
    color: "#991B1B",
    icon: "🥡",
    type: "expense",
    keywords: ["uber eats", "menulog", "deliveroo", "takeaway", "delivery"],
    rules: [],
    isSystem: true,
    isActive: true,
  },

  // Entertainment Categories
  {
    name: "Entertainment",
    color: "#8B5CF6",
    icon: "🎬",
    type: "expense",
    keywords: [],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Streaming Services",
    parentId: "entertainment",
    color: "#7C3AED",
    icon: "📺",
    type: "expense",
    keywords: ["netflix", "spotify", "disney", "amazon prime", "streaming"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Movies & Events",
    parentId: "entertainment",
    color: "#6D28D9",
    icon: "🎭",
    type: "expense",
    keywords: ["cinema", "movie", "theatre", "concert", "event"],
    rules: [],
    isSystem: true,
    isActive: true,
  },

  // Shopping Categories
  {
    name: "Shopping",
    color: "#EC4899",
    icon: "🛍️",
    type: "expense",
    keywords: [],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Clothing",
    parentId: "shopping",
    color: "#DB2777",
    icon: "👕",
    type: "expense",
    keywords: ["clothing", "fashion", "apparel", "shoes", "accessories"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Electronics",
    parentId: "shopping",
    color: "#BE185D",
    icon: "📱",
    type: "expense",
    keywords: ["electronics", "tech", "computer", "phone", "gadget"],
    rules: [],
    isSystem: true,
    isActive: true,
  },

  // Health Categories
  {
    name: "Health & Medical",
    color: "#06B6D4",
    icon: "🏥",
    type: "expense",
    keywords: [],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Medical",
    parentId: "health",
    color: "#0891B2",
    icon: "⚕️",
    type: "expense",
    keywords: ["doctor", "medical", "hospital", "clinic", "health"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Pharmacy",
    parentId: "health",
    color: "#0E7490",
    icon: "💊",
    type: "expense",
    keywords: ["pharmacy", "chemist", "medication", "prescription"],
    rules: [],
    isSystem: true,
    isActive: true,
  },

  // Banking Categories
  {
    name: "Banking & Fees",
    color: "#64748B",
    icon: "🏦",
    type: "expense",
    keywords: [],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Bank Fees",
    parentId: "banking",
    color: "#475569",
    icon: "💳",
    type: "expense",
    keywords: ["fee", "charge", "bank fee", "service fee"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
  {
    name: "Transfers",
    parentId: "banking",
    color: "#334155",
    icon: "↔️",
    type: "transfer",
    keywords: ["transfer", "payment", "send money"],
    rules: [],
    isSystem: true,
    isActive: true,
  },
]
